version: "3.9"
services:
  webserver:
    image: nginx:latest
    volumes: 
      - ./front-end:/usr/share/nginx/html
      - ./front-end/nginx/certs:/etc/nginx/certs
      - ./front-end/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - broker
  broker:
    image: eclipse-mosquitto
    ports:
      - "1884:1884"
      - "1883:1883"
    volumes:
      - ./broker/config:/mosquitto/config
      # - ./broker/data:/mosquitto/data
      # - ./broker/log:/mosquitto/log
      - ./broker/passwords:/mosquitto/passwords